repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami 

environments:
  default:
    values:
      - dev.yaml   

releases:
  - name: postgres
    namespace: {{ env "NAMESPACE" | default "default" }}
    chart: bitnami/postgresql
    version: 10.0.0
    values:     
      - postgresqlUsername: {{ .Values.postgres.username }}
        postgresqlPassword: {{ .Values.postgres.password }}
        postgresqlDatabase: {{ .Values.postgres.database }}
  - name: simple-service
    namespace: {{ env "NAMESPACE" | default "default" }}
    chart: ./charts/simple-service
    needs:
      - {{ env "NAMESPACE" | default "default" }}/postgres
    values: 
      - app:
          db:
            host: postgres-postgresql
            port: 5432
            username: {{ .Values.postgres.username }}
            password: {{ .Values.postgres.password }}
            database: {{ .Values.postgres.database }}